"""empty message

Revision ID: d2f4097afe8f
Revises: de5fd8100ef8
Create Date: 2025-10-29 12:11:36.402683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f4097afe8f'
down_revision: Union[str, Sequence[str], None] = 'de5fd8100ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('phone_number', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('phone_number_org_id_fkey'), 'phone_number', type_='foreignkey')
    op.create_foreign_key(None, 'phone_number', 'organization', ['org_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phone_number', type_='foreignkey')
    op.create_foreign_key(op.f('phone_number_org_id_fkey'), 'phone_number', 'organization', ['org_id'], ['id'])
    op.alter_column('phone_number', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('organization', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
