

services:
  api_service:
    build:
      context: ./api_service
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PG_PORT=${PG_EXTERNAL_PORT}
    ports:
      - 8000:8000
    volumes:
      - "./api_service/core:/app"
    depends_on:
      postgres_service:
        condition: service_healthy
    
  postgres_service:
    build:
      context: ./postgres_service
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - ${PG_EXTERNAL_PORT}:${PG_INTERNAL_PORT}
    volumes:
      - ./postgres_service/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USERNAME} -d ${PG_DATABASE}"]
      interval: 10s
      retries: 5